### ISSUE TITLE
remove ListLIke dependency

### ISSUE THREAD

**Issue by gregwebs** [phadej/aeson-extra#1]
I would consider depending on this package for aeson compatibility, except for that it introduces an extra dependency on ListLIke. Is it possible to remove this dependency? I am not sure what benefit you are getting out of it that you cannot get from the typeclasses in base.

**Comment by gregwebs** [comment]
I looked at CollapsedList more closesly, and I don't believe this is a data structure anyone should be using if they can avoid it. It looks like this helps maintain compatibility with some very dynamically typed JSON. So my preference would be to remove both CollapsedList and ListLIke from the library. Otherwise I think you can get what you need from ListLIke by a combination of Monoid (mempty instead of empty), Applicative (pure instead of singleton) and Foldable (testing the length, head/tail, etc).

**Comment by phadej** [comment]
@gregwebs Yes, I picked `Alternative` over `Monoid`, but for common uses (List and Vector) they fit

**Comment by phadej** [comment]
And to comment about `CollapsedList`, yes I hope no-one uses its `ToJSON` instance. `FromJSON` I needed more than once :/

**Comment by phadej** [comment]
@gregwebs http://hackage.haskell.org/package/aeson-extra-0.2.0.0 published. You're welcome to try it out.

**Comment by gregwebs** [comment]
awesome, thanks!

I have created some of the other pre-value helpers in this package before.
