### ISSUE TITLE
Get it back into stackage nightly (GHC 8 issue?)

### ISSUE THREAD

**Issue by alexanderkjeldaas** [phadej/aeson-extra#21]
It would be great to get this back into stackage nightly.

**Comment by phadej** [comment]
Blocked by:
- https://github.com/ekmett/recursion-schemes/issues/21
- https://github.com/ekmett/parsers/issues/63

**Comment by phadej** [comment]
It's in current nightly https://www.stackage.org/nightly-2017-07-21
