### ISSUE TITLE
Include specific merge functions

### ISSUE THREAD

**Issue by Profpatsch** [phadej/aeson-extra#27]
The merge function from the documentation of [`merge`](https://hackage.haskell.org/package/aeson-extra-0.4.0.0/docs/Data-Aeson-Extra.html#v:merge) is probably the most sensible explicit implementation of a merge (hence the inclusion in `lodash`), so why not include it in `aeson-extra`? Granted, `these` has a few unnecessary dependencies.

**Comment by phadej** [comment]
The dependency on `these` is a least of our worries :)

I'm happy to accept a PR adding `lodashMerge` to the `Merge` module. Please comment that the implementation isn't actually tested against `lodash` proper :)

**Comment by phadej** [comment]
@Profpatsch do you want to make a patch?

**Comment by Profpatsch** [comment]
Yes, I will.

**Comment by phadej** [comment]
@Profpatsch I actually went ahead already, I'll make a release shortly.

**Comment by phadej** [comment]
See #28
