### ISSUE TITLE
Merge Functions

### ISSUE THREAD

**Issue by andrewthad** [phadej/aeson-extra#5]
Take a look at the two functions I propose in this issue: https://github.com/bos/aeson/issues/245

Bos doesn't want them in `aeson` itself, and I completely understand his reasons, so I was thinking about making an `aeson-merge` library, but then I saw your library and thought this might be a good home for them. I propose adding a `Data.Aeson.Merge` module to house these two functions. If this seems agreeable to you, I'll put up a PR.

**Comment by phadej** [comment]
I agree, there are use cases for such functions. [Even I have made my own](https://github.com/phadej/travis-meta-yaml/blob/master/src/Data/Aeson/Merge.hs).

But I also agree with Bryan that behaviour is a bit... un-elegant.

There is now three functions doing about the same stuff, with different twist. If it only could be generalised somehow: some kind of double-traversal of two `Value` producing something third in the process. Like `zip` but for `Value`. That might qualify. Have to think about that.

**Comment by andrewthad** [comment]
I haven't type checked this yet, but here's an idea:

    mergeGeneral :: (HashMap Text Value -> HashMap Text Value -> a) -- object merge
                 -> (Vector Value -> Vector Value -> a) -- list merge
                 -> (Value -> a) -- behavior for other types, how to use the left value
                 -> Bool -- allow nulls to be overridden
                 -> Value
                 -> Value
                 -> a
    mergeGeneral objectMerge arrayMerge conv overrideNull a b = go a b
      where
      go (Object x) (Object y) = objectMerge x y
      go (Array x) (Array y) = arrayMerge x y
      go Null x = if overrideNull then conv x else Null
      go x y = conv x

And it allows us to write the three original functions:

    olegMerge = mergeGeneral (HashMap.mergeWith olegMerge) (\x _ -> Array x) id False
    andrewMerge = mergeGeneral (HashMap.mergeWith andrewMerge) (\x y -> Array (x <> y)) id True
    andrewMergeWithFailure = mergeGeneral (HashMap.mergeWith andrewMergeWithFailure) (\x y -> Just (Array (x <> y))) Just True

What do you think?

**Comment by andrewthad** [comment]
Wait a minute, nevermind. I need to fix something in it.

**Comment by andrewthad** [comment]
The last one should actually be:

andrewMergeWithFailure = mergeGeneral (HashMap.mergeWith andrewMergeWithFailure) (\x y -> Just (Array (x <> y))) (const Nothing) True

And it still doesn't have quite the original behavior because merging anything with `null` will result `Nothing` instead of the other value wrapped in `Just`.

**Comment by phadej** [comment]
Solved in `aeson-extra-0.3.1.0`. 

See `Data.Aeson.Extra.Merge` module
