### ISSUE TITLE
extend aeson support < 0.8

### ISSUE THREAD

**Issue by gregwebs** [phadej/aeson-extra#6]
https://github.com/yesodweb/persistent/issues/499

**Comment by phadej** [comment]
Is `>= 0.7.0.6` enough?

**Comment by gregwebs** [comment]
@yitz I am confused: I thought aeson was a more recent addition to the Haskell platform?

**Comment by phadej** [comment]
@gregwebs @yitz based on https://github.com/hvr/multi-ghc-travis/blob/master/.travis.yml#L44
it seems that you need `aeson-0.6.2.1` as `aeson-0.7` series has `attoparsec >=0.10.2.1` dependency.

TBH, I'd rather unregister old attoparsec.

**Comment by phadej** [comment]
@gregwebs @yitz new revision with `aeson >=0.7.0.6` bound is published. If you need even lower lower bound, I have to think about that...

**Comment by gregwebs** [comment]
Thanks!

**Comment by ygale** [comment]
`aeson 0.7.0.6` should be fine.  It depends on `attoparsec >= 0.11.3.4`, but that's OK; it only requires `text >= 0.11.3.1`, and HP provides `1.1.0.0`.

Thanks!
